### PR TITLE
Android SDK guide in Kotlin - cloud-db/basics

### PR DESCRIPTION
**Pull request by elly0t**
1) Kotlin code has been added
2) Refactored the original Java code as well
3) Refined numerous explanation texts
4) Added an Introduction section, to ensure the readers have the right config before they proceed

Might add some more sections as I feel some more explanations + examples will make things more clear. I'll do this after the other Android docs of cloud-db are done.

### CODE REVIEW

**Comment by Steven-Chan** [comment]
@elly0t Please follow this guide https://chris.beams.io/posts/git-commit/ to write commit message.

**Comment by Steven-Chan** [comment]
The kotlin sample code looks good to me @tensiuyan

**Comment by elly0t** [comment]
@Steven-Chan I have modified the commit messages, please have a look

**Comment by Steven-Chan** [comment]
It looks good enough to me.

Can be even better if you could split the first commit into smaller ones, because from the commit title, you have made several separate changes. You can keep it in mind next time.

**Comment by elly0t** [comment]
@Steven-Chan yeh will do in the future :)

**Pull request merged**
