### PR TITLE
refs. #108 Add guides for setting up FCM and APN

### PR DESCRIPTION
**Pull request by david90**

### CODE REVIEW

**Comment by howawong** [comment]
Possible to include a screenshot in FCM *Obtain the server key from Google Firebase Console* section?

**Comment by carmenlau** [comment]
@chpapa Do you have time to review it? Or need help? thanks!

**Comment by david90** [comment]
I was trying to search for this on doc site. discovered that it's not merged :(

**Comment by chpapa** [comment]
@david90 sorry I dropped it, let me review it now...

**Comment by carmenlau** [comment]
Oh, sorry David. I also forget this.. :(

**Pull request merged**
