### PR TITLE
Container uses Application Context in sample code

### PR DESCRIPTION
**Pull request by seventhmoon**
According to the [API](https://docs.skygear.io/android/reference/io/skygear/skygear/Container.html#defaultContainer-android.content.Context-) spec, `Container.defaultContainer(context)` should pass an Application Context.

### CODE REVIEW

**Comment by seventhmoon** [comment]
I just read the source which actually will get the Application Context, in the first line of the Constructor of `Container` (`this.context = context.getApplicationContext();`).

So, it should be either

1. It does not require Application Context (change the API doc), or 
2. It require Application Context (update the code, check the context, throw Exception if the context is not Application Context).

Personally, I prefer 2 (Strictly on Application Context).
It will make sure user notice that the `Container` instance is along with the `Application`, not `Activity`.

**Comment by chpapa** [comment]
@ben181231 can you help review it?

@Steven-Chan please be noted (since u are doing the sdk API re-grouping)

**Comment by ben181231** [comment]
@seventhmoon

Since the `container` does not keep the reference of the `context` from user, I think it would not cause memory leak from that.

**Comment by seventhmoon** [comment]
Understood. But this should not be affecting option 1 and 2.
Which is about inconsistent between the Guide and the API / JavaDoc.

**Comment by ben181231** [comment]
Oh. I got what you mean. Let me update the JavaDoc.

**Comment by ben181231** [comment]
Close this first. Will update the JavaDoc after API grouping.

**Pull request closed without merging**
