### PR TITLE
Fix JS lambda example

### PR DESCRIPTION
**Pull request by cychiuae**

### CODE REVIEW

**Comment by oursky-travis** [comment]
@cychiuae, thanks for your PR! By analyzing the history of the files in this pull request, we identified @bensonby to be a potential reviewer.

**Comment by chpapa** [comment]
@rickmak this make sense to me, what do you think?

**Comment by cychiuae** [comment]
It turns out we can use js object but object's keys should be matched with argument names in cloud function

**Comment by rickmak** [comment]
The issue here: JS x CloudCode can either support position argument by `array` or keywords args by `object`. Cannot mixed them up.

And if user pass in `object` to trigger lambda with position args, we will try our best to transform the object into correct array by matching the object key and argument names.

**Pull request closed without merging**
